### ISSUE TITLE
Possible Cleanup of old Node Red Files

### ISSUE THREAD

**Issue by Paulf007** [openenergymonitor/emonpi#106]
As node-red was removed from the image , consider removing the old .node-red modules. 
If you install node red-on the emon pi with the installation script node red crashed on startup as there are still old nodes that has not been loaded in the flows.
See below - 

Flows stopped due to missing node types.
emoncms-server
wunderground

**Comment by Steve720** [comment]
Seen here too.  Had to remove /home/pi/.node-red before installing node-red on a fresh install of emonSD-30Oct18.zip.

**Comment by borpin** [comment]
There is work currently in place to replace the creation of an Image file, to an install script that will run on Raspbian Light.  This will solve this problem.  The Image file won't be updated I suspect, just withdrawn.

**Comment by glynhudson** [comment]
Sure, the `~/.node-red` folder will be removed from the next image created using the new build scripts. Apologies for the hassle.
