### ISSUE TITLE
Archive missing v2.83

### ISSUE THREAD

**Issue by JensMunkHansen** [openenergymonitor/emonpi#112]
Hi Developers

I made a typo in the emonhub.conf from the GUI. It puzzled me a lot since using ssh I was looking at a different file. I followed a thread which suggested me to update firmware....

I would very much like to get back to my starting point v2.83 bit it is missing in your archive. Is it possible for you to add it.

Thanks in advance
Jens

**Comment by glynhudson** [comment]
Hi, I would recommend updating to the lastest emonPi FW
