### ISSUE TITLE
factoryreset script out of date

### ISSUE THREAD

**Issue by WeeBull** [openenergymonitor/emonpi#117]
`/opt/openenergymonitor/emonpi/factoryreset` is out of date with respect to the rest of the OS. It tries to access `/home/pi/emonpi` and `/home/pi/data` which don't exist, and then leaves the system in a broken state. In my case, Wi-Fi searching no longer worked in the web setup.

Suggest either fixing or removal.

**Comment by glynhudson** [comment]
This has been fixed, the new factory reset script is located in `/opt/openenergymonitor/EmonScripts/other/factoryreset`. The only factory reset in this emonpi repo will remain for use on older images. 

https://github.com/openenergymonitor/EmonScripts/blob/master/other/factoryreset
