### ISSUE TITLE
emonSD-24Jul20

### ISSUE THREAD

**Issue by antgwms** [openenergymonitor/emonpi#126]
The download link doesn't work or is private, from the website https://guide.openenergymonitor.org/technical/emonpi/ to https://github.com/openenergymonitor/emonpi/Docs/emonSD-pre-built-SD-card-Download-&-Change-Log   I found a community post with the image: https://community.openenergymonitor.org/t/emonsd-24jul20-release/15170

**Comment by glynhudson** [comment]
The correct link is: https://github.com/openenergymonitor/emonpi/wiki/emonSD-pre-built-SD-card-Download-&-Change-Log

Thanks for reporting, I've now fixed the link on the site
