### ISSUE TITLE
download sd image link broken

### ISSUE THREAD

**Issue by ASLABSIT** [openenergymonitor/emonpi#137]
hello 
1) All links except the latest version were not working http 404 not found.
2) Unfortunately the latest version on Raspberry Pi 3 Model A + fails to connect to the network, wpa not active.

main page
https://github.com/openenergymonitor/emonpi/wiki/emonSD-pre-built-SD-card-Download-&-Change-Log

**Comment by glynhudson** [comment]
Hi, 

The older version in insecure and are no longer supported, therefore we made the decision to remove them from download. We don't officially support the Pi model A, however we have tested the latest image and it works on the Pi3A+. There must be another issues here. 

Please, could you post on our community forum https://community.openenergymonitor.org and we'll try and help.

**Comment by ASLABSIT** [comment]
Hi
OK i will investigate a little more, thanks a lot.
Best regards
