### ISSUE TITLE
Does the SD card build doc cover all modifications made

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/emonpi#22]
I note from the [release notes](https://github.com/openenergymonitor/emonpi/wiki/emonSD-pre-built-SD-card-Download-&-Change-Log) for the latest SD Card build, there is reference to a number of changes that do not seem to be included in the [build doc](https://github.com/openenergymonitor/emonpi/blob/master/docs/SD-card-build.md).

(copied from change log)
-     Symlink fstab in emonpi repo to /etc/fstab to allow updating
-     Reduce garbage in /var/log/messages but to Raspbian bug
-     Fix log rotate to includue all log files to ensure /var/log does not fill up
-     Fix node-RED flows to survive update cycle (??? not sure if this is in the NodeRed Guide)
-     Trim SD card (allow 60mB of unallocated partition) to fit on all (or majority) of 4GB SD cards, shop pre-built SD cards included with emonPi / emonBase will be 8GB with ~/data partition expanded accordingly.
-     Generate new SSH keys

Some of these are really useful in general so would be good to capture :)

**Comment by glynhudson** [comment]
All the things mentioned are incorporated into files which are either symlinked or copied into place during the image build. I will try and elaborate: 

> Symlink fstab in emonpi repo to /etc/fstab to allow updating

simply symlink /etc/fstab to [~/emonpi/fstab](https://github.com/openenergymonitor/emonpi/blob/master/fstab)

> Reduce garbage in /var/log/messages but to Raspbian bug

[info added here](https://github.com/openenergymonitor/emonpi/blob/master/docs/SD-card-build.md#8-low-write-mode-emoncms-optimisations)

> Fix log rotate to includue all log files to ensure /var/log does not fill up

`sudo chown root:root /etc/logrotate.conf` [done via update script](https://github.com/openenergymonitor/emonpi/blob/dev/emoncmsupdate#L179)

> Fix node-RED flows to survive update cycle (??? not sure if this is in the NodeRed Guide)

Move node red data folder back to /home/pi but symlink to /home/pi/data. Documented on nodeRED readme https://github.com/openenergymonitor/oem_node-red/commit/b5e84b82567d1065cbeb809205d05e26f3362785

> Trim SD card (allow 60mB of unallocated partition) to fit on all (or majority) of 4GB SD cards, shop pre-built SD cards included with emonPi / emonBase will be 8GB with ~/data partition expanded accordingly.

Manual operation using gparted after SD card is imaged 

> Generate new SSH keys

factoryreset script item https://github.com/openenergymonitor/emonpi/blob/master/factoryreset#L149
