### ISSUE TITLE
Lastest emonSD image updates on every reboot!

### ISSUE THREAD

**Issue by pb66** [openenergymonitor/emonpi#38]
Latest build and fully updated.

My emonPi updates on every reboot, it seems the "firstbootupdate" script is initializing an update even when it is not required. When I looked into it and tested the separate "or" parts of the if statement in this line 

https://github.com/openenergymonitor/emonpi/blob/master/firstbootupdate#L13

I found the log file is non-zero size as expected since it is not the first boot, but the $button value is 0 at rest and 1 when pressed, so the button action actually works as a "update bypass" if held while rebooting not a "forced update". 

By editing this line to 

    if [ ! -s /home/pi/data/emonpiupdate.log ] || [ $button == 1 ]; then

it works as expected.

I can see there was a [recent change](https://github.com/openenergymonitor/emonpi/commit/44f5aa70f050cdb41e36110ab4e361653e9284af) to this code that inverted the action based on the $button value, was this intended? has the switch been physically changed in production?

**Comment by glynhudson** [comment]
Good spot, I got the GPIO state inverted. It's been fixed now. Thanks 👍

**Comment by pb66** [comment]
Cool! thanks.
I submitted PR to change the comment to suit #39 too

**Comment by glynhudson** [comment]
Great, thanks!

- sent from my mobile device
