### ISSUE TITLE
Factory reset does not remove ssh authorised keys

### ISSUE THREAD

**Issue by GeorgeBrooke** [openenergymonitor/emonpi#48]
I ran the factory rest script on the latest SD card image as part of debugging a feeds issue and after the system had been cleaned and the Pi had rebooted I was still able to login using the previously setup authorised key.

**Comment by glynhudson** [comment]
Thanks for letting us know. Where are the keys stored? The factory reset script removes both: 

```
sudo rm /home/pi/.ssh/known_hosts
sudo rm /etc/ssh/ssh_host_*
```

**Comment by GeorgeBrooke** [comment]
I'm talking about the `/home/pi/.ssh/authorized_keys` file which holds the public keys authorised to login to the system without a password.
Since the factory reset resets the pi password (to the raspberian default rather than the emonpi default) I would have thought it sensible to also remove these keys?

**Comment by GeorgeBrooke** [comment]
I would suggest changing `sudo rm /home/pi/.ssh/known_hosts` to `sudo rm /home/pi/.ssh/*` as that would also take out any ssh user keys (e.g. used for automated push backups) unless there was a deliberate decision to keep them.

**Comment by glynhudson** [comment]
Good idea, thanks 👍
