### ISSUE TITLE
EmonSD Build Guide Error on Installing EmonHUB

### ISSUE THREAD

**Issue by davidski** [openenergymonitor/emonpi#55]
The [SD-card-build.md](https://github.com/openenergymonitor/emonpi/blob/master/docs/SD-card-build.md) document currently reads: 

```
The emon-pi variant of emonHub locates the config file in the RW partition /home/pi/data/emonhub.conf, this config file includes the default emonpi MQTT authentication details. Symlink the latest default config file:

	sudo rm ~/data/emonhub.conf
	sudo ln -s /home/pi/emonhub/conf/emonpi.default.emonhub.conf /home/pi/data/emonhub.conf

	sudo service emonhub start
```

The `emonhub/install` process the user is instructed to launch just prior to this step moves the `emonpi.default.emonhub.conf` file to the `/home/pi/data` directory, causing:

1. the `ln -s` to link to a non-existent file
2. `emonhub` to fail to start
3. much sadness :sob:

The above quoted section can either be removed completely from the build doc or comments can be added that this is an optional step if not running `emonhub/install`. I vote for removing completely. :smile:

**Comment by glynhudson** [comment]
Thanks, fixed 👍 

Sorry for the hassle.
