### ISSUE TITLE
Postprocess Module Included in SD Image?

### ISSUE THREAD

**Issue by davidski** [openenergymonitor/emonpi#57]
Is the postprocess module intended to be included in the stock SD image? It's not currently in the listed default modules, though I have it on my Nov 2016 image, possibly as a result of having run the emoncms update script, which appears to install that module.

Seeking clarification before I add this to the default module list in my Chef-version of the build process. :smile:

**Comment by JonMurphy** [comment]
this should help!  
https://community.openenergymonitor.org/t/post-process-disappeared/4583?u=jon

**Comment by davidski** [comment]
Thanks, @JonMurphy! Looking through that thread and the `emoncms/postprocess` repo, it looks like the postprocess module has existed as a stand alone module for a while and should be included in the emonSD setup process. If you or another contributor could confirm that that's correct, I'll get an issue opened on the emonSD repo.

**Comment by TrystanLea** [comment]
Yes I can confirm postprocess module is included and I plan to announce and write a guide for it soon :)
