### ISSUE TITLE
SDCard build steps ordering problem.

### ISSUE THREAD

**Issue by greeebs** [openenergymonitor/emonpi#58]
In emonpi/docs/SD-card-build.md this line fails:
> sudo sh -c 'echo "extension=mosquitto.so" > /etc/php5/apache2/conf.d/20-mosquitto.ini'

because apache isn't installed yet. 

I wonder if section 5 (Installing MQTT) should follow after section 7 (Installing emonCMS) which is where apache is installed?

I've also noticed that section 6 is missing - probably should have been associated with this heading:
>## Install emonHub

EDIT: while I'm here... there's also an extraneous double quote (”) on the end of this line:
> sudo apt-get install -y python-pip python-serial python-configobj”

**Comment by glynhudson** [comment]
Thanks, this has now been fixed
