### ISSUE TITLE
User pi

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/emonpi#91]
https://github.com/openenergymonitor/emonpi/blob/0c477c895f3eb198bf821c79cd068f396631cf12/install/init.sh#L3-L3

Could the current user be used instead of `pi` or else pass in a parameter for the user?

Thinking is making it non-rpi specific

**Comment by TrystanLea** [comment]
Fixed here, thanks: https://github.com/openenergymonitor/emonpi/commit/f3a63c9b3012c42c98abdcc96fdbdcd1a8d5f589
