### ISSUE TITLE
Install packages by apt in sub scripts

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/emonpi#93]
https://github.com/openenergymonitor/emonpi/blob/0c477c895f3eb198bf821c79cd068f396631cf12/install/main.sh#L43-L43

These should be with the relevant sub script.

If I do not select Apache for being installed, I would not expect an `apt-get apache` command to be run.

**Comment by TrystanLea** [comment]
Fixed here: https://github.com/openenergymonitor/emonpi/commit/d4936e567953d505dfe1d9ca60ac0292a42ef982

thanks
