### ISSUE TITLE
Installation of Mosquitto server and mosquitto extension should be separated.

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/emonpi#95]
https://github.com/openenergymonitor/emonpi/blob/0c477c895f3eb198bf821c79cd068f396631cf12/install/mosquitto.sh#L7-L7

There will be instances where the Mosquitto server is not desirable when there is already an MQTT server in use.

**Comment by TrystanLea** [comment]
Great, added the options
https://github.com/openenergymonitor/emonpi/commit/59d12440369b06ffd35ba7f6b44c95a3ac8fb12e
