### ISSUE TITLE
Use systemctl for services

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/emonpi#96]
https://github.com/openenergymonitor/emonpi/blob/0c477c895f3eb198bf821c79cd068f396631cf12/install/apache.sh#L27-L27

```
sudo systemctl restart apache2
```

**Comment by glynhudson** [comment]
The two commands seem to be interchangeable. Both work on my emonPi. Is there any advantage to maintaining backward compatibility?

**Comment by borpin** [comment]
`service` is a wrapper that trys `init.d`, then `systemd` then `SysV`.

`systemctl` has more functionality (e.g. the mask command, list etc) and is the correct tool to use for managing systemd based init services.

**Comment by TrystanLea** [comment]
Thanks @borpin changed to systemctl
https://github.com/openenergymonitor/emonpi/commit/226e318922e0da439379233ed25d544caca97320
