### ISSUE TITLE
Duplicate daemon.log logging

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/emonpi#97]
https://github.com/openenergymonitor/emonpi/blob/05e5dba2932da71d46da9d277d266864b6038e71/install/emonsd.sh#L40-L40

This line is intended to prevent duplicate daemon.log entries.  My standard EmonPi does not have this line in the `rsyslog.conf`

**Comment by TrystanLea** [comment]
I've commented out this line now, following our discussion of handling emonhub.log differently 
https://github.com/openenergymonitor/emonpi/commit/b614413fb888d6eae3167b38a02c4e433bb71b17
